#!/bin/bash

# Set the CUDA_VISIBLE_DEVICES variable
export CUDA_VISIBLE_DEVICES=MIG-8da94119-5f41-5ca3-af3f-db7ef198db42

# Print the value of CUDA_VISIBLE_DEVICES
echo "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES"