#!/bin/bash

# Set the CUDA_VISIBLE_DEVICES variable
export CUDA_VISIBLE_DEVICES=MIG-c523ae8e-e2cb-529f-9f61-40d515259b57

# Print the value of CUDA_VISIBLE_DEVICES
echo "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES"