#!/bin/bash
export OMP_NUM_THREADS=16
export MKL_NUM_THREADS=16
export OPENBLAS_NUM_THREADS=16
export NUMEXPR_NUM_THREADS=16
export TBB_NUM_THREADS=16
# Set the CUDA_VISIBLE_DEVICES variable
export CUDA_VISIBLE_DEVICES=MIG-705c9c11-d339-5a1b-8623-fd2eccf07871

# Print the value of CUDA_VISIBLE_DEVICES
echo "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES"