export OMP_NUM_THREADS=16
export MKL_NUM_THREADS=16
export OPENBLAS_NUM_THREADS=16
export NUMEXPR_NUM_THREADS=16
export TBB_NUM_THREADS=16
export CUDA_VISIBLE_DEVICES=MIG-5fc13c84-c5b6-54aa-9151-439b2bcd020d

# Print the value of CUDA_VISIBLE_DEVICES
echo "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES"