#!/bin/bash
export OMP_NUM_THREADS=32
export MKL_NUM_THREADS=32
export OPENBLAS_NUM_THREADS=32
export NUMEXPR_NUM_THREADS=32
export TBB_NUM_THREADS=32
# Set the CUDA_VISIBLE_DEVICES variable
export CUDA_VISIBLE_DEVICES=MIG-b0e6eb73-7cce-5da1-a4a1-320ef7fafe71

# Print the value of CUDA_VISIBLE_DEVICES
echo "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES"