export OMP_NUM_THREADS=32
export MKL_NUM_THREADS=32
export OPENBLAS_NUM_THREADS=32
export NUMEXPR_NUM_THREADS=32
export TBB_NUM_THREADS=32

export CUDA_VISIBLE_DEVICES=MIG-7ceda8f0-e7bc-59de-ad33-1ce9121f2a28

# Print the value of CUDA_VISIBLE_DEVICES
echo "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES"